name: Deploy Docker to Azure VM

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  DOCKERHUB_REPOSITORY_CLIENT: ${{ secrets.DOCKERHUB_REPOSITORY_CLIENT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker compose build --no-cache
          docker compose push

      - name: Deploy the Docker image to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          envs: DOCKERHUB_USERNAME, DOCKERHUB_ACCESS_TOKEN
          script: |
            # Navigate to the directory where Docker Compose is executed
            cd Terre/

            git pull

            # Log in to DockerHub
            sudo docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN

            # Stop and remove the previous Docker session
            sudo docker compose down
            
            # Pull the latest images
            sudo docker compose pull

            # Start the containers using Docker Compose
            sudo docker compose run --rm -v /etc/letsencrypt/live/:/etc/nginx/ssl -p 443:443 -p 80:80 client